### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by koipkoi** [koipkoi/galmuri-condensed#1]
- [ ] pixel font maker로 폰트 그리기
- [ ] 완성된 pfp파일에서 자소 픽셀 데이터 추출
- [ ] 추출된 데이터를 7x9.png에 다시 입력

**Comment by koipkoi** [comment]
- [ ] 'ㅌ', 'ㄹ' 등 높은 공간의 자음 필요
